#!/bin/bash

[ -e demo ] && rm demo;

gcc aurora5.c libs/setup/shell.c libs/utils/aucolors.c libs/utils/Common.c libs/setup/FirstSetup.c  -o demo;

[ -e demo ] && ./demo;

[ -e demo ] && rm demo;

rm -R etc 2> /dev/null




